server.port: 8081
application.rememberMe.key: ${remember_me_key}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_Username} #enter your username to database
    password: ${DB_Password} #enter your password to database
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: ${Email_Username} #enter email from whit will be send message with token
    password: ${Email_Password} #enter password from email that will send message
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true