spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bills?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ksciuk12
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: bill-logic
server:
  port: 0
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka