spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bills?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ksciuk12
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    username: mkbills981@gmail.com
    password: ksciuk12
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true