application:
  rememberMe:
    key: "secretTokenHashKey21GA21-21FSAGSAW"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bills?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root #enter your username to database
    password: ksciuk12 #enter your password to database
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: todo #enter email from whit will be send message with token
    password: todo #enter password from email that will send message
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true